### ISSUE TITLE
Data Science Cheatsheet!

### ISSUE THREAD

**Issue by harshajk** [harshajk/cheatsheets#1]

**Comment by starxa2** [comment]
do you need a cheatsheet ?

**Comment by harshajk** [comment]
Yes! Looking for one!

**Comment by starxa2** [comment]
any specific topic you want to get a cheatsheet on ? because data science is very big 😁👍

**Comment by starxa2** [comment]
you can easily find one at https://www.datacamp.com/community/data-science-cheatsheets

**Comment by starxa2** [comment]
Good luck !!

**Comment by harshajk** [comment]
Thanks @starxa2 !
